<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGPUQ7pF\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGPUQ7pF/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerGPUQ7pF.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerGPUQ7pF\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerGPUQ7pF\appAppKernelProdContainer([
    'container.build_hash' => 'GPUQ7pF',
    'container.build_id' => '4f82578a',
    'container.build_time' => 1694197335,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGPUQ7pF');
